name: Continuous Deployment

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    name: Build Plugin
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: |
          npm install --global sodium-native@5.0.10
          echo "NODE_PATH=$(npm root -g)" >> $GITHUB_ENV
      - name: Setup Hytale Server Jar
        id: setup_hytale_server
        run: |
          mkdir hytale-server
          cd hytale-server

          # Download Hytale Server Downloader
          wget https://downloader.hytale.com/hytale-downloader.zip
          unzip hytale-downloader.zip
          rm hytale-downloader.zip

          # Download Hytale Server using API Key
          echo '${{ secrets.HYTALE_API_KEY }}' > .hytale-downloader-credentials.json
          # Log first 10 characters to verify file creation (for debugging purposes)
          head -c 30 .hytale-downloader-credentials.json
          ./hytale-downloader-linux-amd64
          unzip *.zip
          echo "HYTALE_API_KEY=$(cat .hytale-downloader-credentials.json)" >> $GITHUB_OUTPUT

          # Move server jar to expected location
          INSTALL_DIR=~/.var/app/com.hypixel.HytaleLauncher/data/Hytale/install/release/package/game/latest/Server/
          mkdir -p $INSTALL_DIR
          mv Server/*.jar $INSTALL_DIR
      - name: Update HYTALE_API_KEY Secret
        uses: actions/github-script@v8
        env:
          HYTALE_API_KEY: ${{ steps.setup_hytale_server.outputs.HYTALE_API_KEY }}
        with:
          result-encoding: string
          github-token: ${{ secrets.PERSONAL_TOKEN }}
          script: |
            const sodium = require('sodium-native');
            const { data: {key: publicKey, key_id: keyId} } = await github.rest.actions.getRepoPublicKey({...context.repo});
            if (publicKey) {
              const key = Buffer.from(publicKey, 'base64');
              const message = Buffer.from(process.env.HYTALE_API_KEY);
              const ciphertext = Buffer.alloc(message.length + sodium.crypto_box_SEALBYTES);

              sodium.crypto_box_seal(ciphertext, message, key);
              const encryptedToken = ciphertext.toString('base64');

              await github.rest.actions.createOrUpdateRepoSecret({
                ...context.repo, 
                secret_name: 'HYTALE_API_KEY',
                encrypted_value: encryptedToken,
                key_id: keyId,
              });
            } else {
              core.error('Failed to fetch the public key. Unable to update secret');
            }
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: PluginArtifact
          path: build/libs/*.jar

  create-release:
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v6
        with:
          name: PluginArtifact
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.PERSONAL_TOKEN }}
          name: Release ${{ github.ref_name }}
          body: |
            Release version ${{ github.ref_name }} has been created.
          generate_release_notes: true
          files: "*.jar"
