name: Release Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true
        default: "v0.0.0"

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
        uses: actions/checkout@v6

      - name: Update version
        id: update_version
        run: |
          GRADLE="gradle.properties"
          VERSION_INPUT="${{ github.event.inputs.version }}"
          VERSION="${VERSION_INPUT#v}"
          echo "Updating version to $VERSION in $GRADLE"
          sed -i "s/^version=.*/version=$VERSION/" $GRADLE
          echo "Updated version to $VERSION"

      - name: Create PR
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          commit-message: "Updated version to ${{ github.event.inputs.version }}"
          branch: chore/release-version-${{ github.event.inputs.version }}
          title: "Release version ${{ github.event.inputs.version }}"
          body: "This PR releases the version ${{ github.event.inputs.version }}."
          base: main
          sign-commits: true
          labels: release-version
